### ISSUE TITLE
Ошибка с памятью в хроме 32-bit

### ISSUE THREAD

**Issue by Ser-Gen** [pixhub-int/image-processing#1]
```
Uncaught (in promise) RangeError: Invalid typed array length: undefined
    at new Int8Array (<anonymous>)
    at updateGlobalBufferViews (http://10.36.120.83/image-compressor/butteraugli/butteraugli.js:1:8888)
    at enlargeMemory (http://10.36.120.83/image-compressor/butteraugli/butteraugli.js:1:10763)
    at wasm-function[33]:57
    at wasm-function[39]:3234
    at wasm-function[144]:48
    at wasm-function[62]:32
    at wasm-function[28]:98
    at wasm-function[105]:107
    at wasm-function[32]:91
```

**Comment by Ser-Gen** [comment]
В ФФ 32- и 64-битном не воспроизводится.
